### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by RaafatTurki** [ariasmn/ugm#1]
Is it planned?

**Comment by ariasmn** [comment]
Hi @RaafatTurki !

Given my limited time and how easy is to just get the tool either using Go itself or by downloading the binary, I don't have any plans for AUR support, sorry.

Thanks for the support.

**Comment by RaafatTurki** [comment]
@ariasmn Understandable.
What about someone else maintaining it?

**Comment by ariasmn** [comment]
@RaafatTurki Obviously, if somebody else wants to do the work I wouldn't say no :)
